// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "pRRE06zriBI80wuQkIrj22BiNzSgUvPBNnDzsvZPpb9Dfh6fxSrCMrzreG14twsYxx6fRP";
}
}
}

